apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-api
  description: A sample API that provides weather forecast information.
  annotations:
    github.com/project-slug: rrrraj729/Wheather-api
    # backstage.io/api-spec: url/to/weather-api-swagger.json # Replace this with the URL or file path to the Swagger JSON file
spec:
  type: openapi
  lifecycle: production
  owner: rahul.raj@talentica.com
  definition: https://raw.githubusercontent.com/rrrraj729/Wheather-api/refs/heads/Talentica-backstage-integration/Wheather-api/api/weather-api-swagger.json?token=GHSAT0AAAAAACYOP2JJJF3VCBXHGC54SXIEZYDR2KQ
